# Dockerfile for azcli

FROM mcr.microsoft.com/azure-cli:latest
MAINTAINER LorraineLiu <410169554@qq.com>

RUN mkdir -p /src/azcli
ADD tmp/azcli /src/azcli
ENV PYTHONPATH /src/azcli

RUN pip install --trusted-host=mirrors.aliyun.com -i http://mirrors.aliyun.com/pypi/simple -r requirements.txt
